# See: https://docs.travis-ci.com/user/languages/c/
language: c
sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - _CC="gcc-8 -std=c11"
        - _CXX="g++-8 -std=c++17"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - _CC="clang-6.0 -std=c11"
        - _CXX="clang++-6.0 -std=c++17"
before_install:
  - export CC="$_CC" CXX="$_CXX"
script:
  - make && make check
